
all:
	  g++ -L/usr/local/lib -lfltk -lXext -lX11 -lm  "wordyade.cxx"  -o wordyade 

   
install:
	    cp wordyade /usr/local/bin/ ; chmod +x /usr/local/bin/wordyade 

test:
	  gcc test.c -o test    

