// generated by Fast Light User Interface Designer (fluid) version 1.0302

#include "wordyade.h"
#include "func.c"
#include "fl.c"

int main(int argc,char *argv[]) {
  textbuf = new Fl_Text_Buffer;
    style_init();
  
    Fl_Window* window = new_view();
  
    window->show(1, argv);
  
    if (argc > 1) load_file(argv[1], -1);
  
    return Fl::run();
}
